export const dummySkills: SkillRecord[] = [
	{
		id: "1",
		title: "OpenAI GPT-4",
		slug: "openai-gpt4",
		description:
			"Advanced large language model capable of understanding and generating human-like text with reasoning capabilities",
		category: "AI Model",
		tags: ["ai", "llm", "nlp", "chatbot"],
		installCommand: "npm install openai",
		createdAt: "2026-01-15T10:30:00Z",
		authorClerkId: "user_123",
		authorEmail: "developer@example.com",
	},
	{
		id: "2",
		title: "Anthropic Claude",
		slug: "anthropic-claude",
		description:
			"Constitutional AI assistant focused on safety and helpfulness with advanced reasoning abilities",
		category: "AI Model",
		tags: ["ai", "claude", "safety", "reasoning"],
		installCommand: "npm install @anthropic-ai/sdk",
		createdAt: "2026-02-20T14:45:00Z",
		authorClerkId: "user_456",
		authorEmail: "dev@example.com",
	},
	{
		id: "3",
		title: "LangChain",
		slug: "langchain",
		description:
			"Framework for developing applications powered by language models with chains, agents, and memory",
		category: "AI Framework",
		tags: ["ai", "framework", "agents", "chains"],
		installCommand: "npm install langchain",
		createdAt: "2026-03-10T09:15:00Z",
		authorClerkId: null,
		authorEmail: null,
	},
	{
		id: "4",
		title: "AutoGPT",
		slug: "autogpt",
		description:
			"Autonomous AI agent that chains together LLM thoughts to accomplish complex goals independently",
		category: "AI Agent",
		tags: ["ai", "autonomous", "agent", "automation"],
		installCommand: "pip install autogpt",
		createdAt: "2026-04-05T16:20:00Z",
		authorClerkId: "user_789",
		authorEmail: "backend@example.com",
	},
	{
		id: "5",
		title: "Hugging Face",
		slug: "hugging-face",
		description:
			"Open-source platform for machine learning models, datasets, and collaborative AI development",
		category: "AI Platform",
		tags: ["ai", "ml", "models", "datasets"],
		installCommand: "npm install @huggingface/inference",
		createdAt: "2026-05-12T11:00:00Z",
		authorClerkId: null,
		authorEmail: null,
	},
];
