/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkillsIndexRouteImport } from './routes/skills/index'
import { Route as SkillsNewRouteImport } from './routes/skills/new'
import { Route as SkillsIdRouteImport } from './routes/skills/$id'
import { Route as ApiWebhooksClerkRouteImport } from './routes/api/webhooks/clerk'
import { Route as _authSignUpSplatRouteImport } from './routes/__auth/sign-up.$'
import { Route as _authSignInSplatRouteImport } from './routes/__auth/sign-in.$'

const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsNewRoute = SkillsNewRouteImport.update({
  id: '/skills/new',
  path: '/skills/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIdRoute = SkillsIdRouteImport.update({
  id: '/skills/$id',
  path: '/skills/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksClerkRoute = ApiWebhooksClerkRouteImport.update({
  id: '/api/webhooks/clerk',
  path: '/api/webhooks/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const _authSignUpSplatRoute = _authSignUpSplatRouteImport.update({
  id: '/__auth/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const _authSignInSplatRoute = _authSignInSplatRouteImport.update({
  id: '/__auth/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/saved': typeof SavedRoute
  '/skills/$id': typeof SkillsIdRoute
  '/skills/new': typeof SkillsNewRoute
  '/skills/': typeof SkillsIndexRoute
  '/sign-in/$': typeof _authSignInSplatRoute
  '/sign-up/$': typeof _authSignUpSplatRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/saved': typeof SavedRoute
  '/skills/$id': typeof SkillsIdRoute
  '/skills/new': typeof SkillsNewRoute
  '/skills': typeof SkillsIndexRoute
  '/sign-in/$': typeof _authSignInSplatRoute
  '/sign-up/$': typeof _authSignUpSplatRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/saved': typeof SavedRoute
  '/skills/$id': typeof SkillsIdRoute
  '/skills/new': typeof SkillsNewRoute
  '/skills/': typeof SkillsIndexRoute
  '/__auth/sign-in/$': typeof _authSignInSplatRoute
  '/__auth/sign-up/$': typeof _authSignUpSplatRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/saved'
    | '/skills/$id'
    | '/skills/new'
    | '/skills/'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/api/webhooks/clerk'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/saved'
    | '/skills/$id'
    | '/skills/new'
    | '/skills'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/api/webhooks/clerk'
  id:
    | '__root__'
    | '/'
    | '/saved'
    | '/skills/$id'
    | '/skills/new'
    | '/skills/'
    | '/__auth/sign-in/$'
    | '/__auth/sign-up/$'
    | '/api/webhooks/clerk'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SavedRoute: typeof SavedRoute
  SkillsIdRoute: typeof SkillsIdRoute
  SkillsNewRoute: typeof SkillsNewRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
  _authSignInSplatRoute: typeof _authSignInSplatRoute
  _authSignUpSplatRoute: typeof _authSignUpSplatRoute
  ApiWebhooksClerkRoute: typeof ApiWebhooksClerkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/new': {
      id: '/skills/new'
      path: '/skills/new'
      fullPath: '/skills/new'
      preLoaderRoute: typeof SkillsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$id': {
      id: '/skills/$id'
      path: '/skills/$id'
      fullPath: '/skills/$id'
      preLoaderRoute: typeof SkillsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/clerk': {
      id: '/api/webhooks/clerk'
      path: '/api/webhooks/clerk'
      fullPath: '/api/webhooks/clerk'
      preLoaderRoute: typeof ApiWebhooksClerkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__auth/sign-up/$': {
      id: '/__auth/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof _authSignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__auth/sign-in/$': {
      id: '/__auth/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof _authSignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SavedRoute: SavedRoute,
  SkillsIdRoute: SkillsIdRoute,
  SkillsNewRoute: SkillsNewRoute,
  SkillsIndexRoute: SkillsIndexRoute,
  _authSignInSplatRoute: _authSignInSplatRoute,
  _authSignUpSplatRoute: _authSignUpSplatRoute,
  ApiWebhooksClerkRoute: ApiWebhooksClerkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
